on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
  commitNotes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Commit Notes
        run: |
          # Retrieve the latest commit SHA
          commit_sha=$(git rev-parse HEAD)

          # Fetch the commit details using the GitHub API
          response=$(curl -s -H "Accept: application/vnd.github.v3+json" \
                      https://api.github.com/repos/${{ github.repository }}/commits/${commit_sha})

          # Extract the commit message from the API response
          commit_message=$(echo $response | jq -r '.commit.message')

          echo "Commit Message:=> $commit_message"
  testing-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Get CommitRelease Notes
        uses: actions/checkout@v2
      - run: |
          echo "repo: ${{ github.repository_name }}"
          echo "owner: ${{ github.repository_owner }}"          
          echo "sha: ${{ steps.hello.outputs.sha }}"

        